name: test

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ 3.1, '3.0', 2.7, head, truffleruby-head ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - ruby: mswin
            os: windows-latest
          - ruby: mingw
            os: windows-latest
        exclude:
          - ruby: head
            os: windows-latest
          - ruby: truffleruby-head
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run test
      run: bundle exec rake compile test
